# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_auto_20191022_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
