# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-22 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0004_auto_20191022_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaapp.Profile'),
        ),
    ]
